version: '3.8'

services:
  cookies-app:
    container_name: cookies-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"   # Map cổng 5000 máy ngoài vào 8080 trong container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CookiesAuthenDb=Server=192.168.1.225,1433;Database=MyLearningDB;User Id=sa;Password=123456aA@;TrustServerCertificate=True;MultipleActiveResultSets=true
    #restart: unless-stopped